version: 2.1
jobs:
    build:
        docker:
            - image: cimg/node:14.15
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: yarn
            - run:
                  command: |
                      yarn build
            - persist_to_workspace:
                  root: .
                  paths:
                      - node_modules
                      - build

    build_image_and_push:
        docker:
            - image: cimg/base:2020.01
              auth:
                username: $DOCKER_HUB_USERNAME
                password: $DOCKER_HUB_TOKEN
        environment:
            - ORGANIZATION_NAME: 'dronehandelen'
            - PROJECT_NAME: 'frontend'
        steps:
            - setup_remote_docker
            - checkout
            - attach_workspace:
                  at: .
            - docker/build:
                  cache_from: ${ORGANIZATION_NAME}/${PROJECT_NAME}:latest
                  image: ${ORGANIZATION_NAME}/${PROJECT_NAME}
                  tag: ${CIRCLE_SHA1},latest
                  extra_build_args: '--target prod'
            - docker/push:
                  image: ${GOOGLE_PROJECT_ID}/${PROJECT_NAME}
                  tag: ${CIRCLE_SHA1}
            - docker/push:
                  image: ${GOOGLE_PROJECT_ID}/${PROJECT_NAME}
                  tag: latest

orbs:
    node: circleci/node@4.1.0
    docker: circleci/docker@1.5.0

workflows:
    version: 2
    build_push_deploy:
        jobs:
            - build:
                  context: hub
                  filters:
                      branches:
                          only: master
            - build_image_and_push:
                  context: hub
                  requires:
                      - build
                  filters:
                      branches:
                          only: master
