version: 2.1
jobs:
    build:
        docker:
            - image: cimg/node:14.15
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: yarn
            - run:
                  command: |
                      yarn build
            - persist_to_workspace:
                  root: .
                  paths:
                      - node_modules
                      - build

orbs:
    node: circleci/node@4.1.0
    docker: circleci/docker@1.5.0

workflows:
    version: 2
    build_push_deploy:
        jobs:
            - build:
                  context: hub
                  filters:
                      branches:
                          only: master
            - docker/publish:
                attach-at: ./
                cache_from: ${ORGANIZATION_NAME}/${PROJECT_NAME}:latest
                image: ${ORGANIZATION_NAME}/${PROJECT_NAME}
                tag: ${CIRCLE_SHA1},latest
                extra_build_args: '--target prod'
                docker-username: DOCKER_HUB_USERNAME
                docker-password: DOCKER_HUB_TOKEN
                context: hub
                requires:
                    - build
                filters:
                    branches:
                        only: master
